kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: clean and install dependencies
    image: node
    commands:
      - rm package-lock.json
      - rm -rf node_modules
      - npm install

  - name: lint check
    image: node
    commands:
      - npm run lint
